### ISSUE TITLE
~3 sec delay between writing to  Acquire and the start of the acquisition 

### ISSUE THREAD

**Issue by oksanagit** [epics-modules/xspress3#23]
One our user uses xspress3 in a step scan mode: (moves monochromator, acquires one spectra) x N. It appears  there is a few seconds delay between writing 1 to Acquire and the start of the acquisition. To debug it and get some numbers,  I enabled traceflow.  
```.....................
2021/06/23 14:27:13.449 XSP3 addr 0 queueRequest priority 0 not lockHolder
2021/06/23 14:27:13.449 XSP3 addr 0 queueRequest priority 0 not lockHolder
2021/06/23 14:27:13.449 asynManager::portThread port=XSP3 callback
2021/06/23 14:27:13.449 asynManager::portThread port=XSP3 callback
2021/06/23 14:27:13.508 XSP3 addr 0 queueRequest priority 0 not lockHolder
2021/06/23 14:27:13.509 asynManager::portThread port=XSP3 callback
2021/06/23 14:27:13.509 Xspress3::writeInt32 Calling writeInt32.
2021/06/23 14:27:13.509 Xspress3::writeInt32 asynUser->reason: 8, value: 1, addr: 0
2021/06/23 14:27:13.509 Xspress3::checkConnected Checking connected status.
2021/06/23 14:27:13.509 Xspress3::writeInt32 Starting Data Collection.
2021/06/23 14:27:13.549 XSP3 addr 0 queueRequest priority 0 not lockHolder
2021/06/23 14:27:13.549 XSP3 addr 0 queueRequest priority 0 not lockHolder
xsp4_system_start_count_enb: Xsp3Sys[path].run_flags=0xC
2021/06/23 14:27:17.159 Xspress3::writeInt32 Started Data Collection.
2021/06/23 14:27:17.159 asynManager::portThread port=XSP3 callback
2021/06/23 14:27:17.159 asynManager::portThread port=XSP3 callback
2021/06/23 14:27:17.159 Got start event.
2021/06/23 14:27:17.159 Collect 1 frames
2021/06/23 14:27:17.249 XSP3 addr 0 queueRequest priority 0 not lockHolder
2021/06/23 14:27:17.249 XSP3 addr 0 queueRequest priority 0 not lockHolder
2021/06/23 14:27:17.249 asynManager::portThread port=XSP3 callback
2021/06/23 14:27:17.249 asynManager::portThread port=XSP3 callback
2021/06/23 14:27:17.349 XSP3 addr 0 queueRequest priority 0 not lockHolder
2021/06/23 14:27:17.349 XSP3 addr 0 queueRequest priority 0 not lockHolder
...................................... ```
 The message flow does stop for a few seconds indeed. I would appreciate help figuring out the source of the delay and hopefully eliminating it. 
Thank you

**Comment by newville** [comment]
@oksanagit I don't fully understand the messages or what you are concluding from that.  It looks like it started collecting at
14:27:13.509 and again at 14:27:17.159.... Was acquisition started twice?   Was there an ERASE that happened or something?

My experience is that there is about 0.5-second between hitting acquire and the detector actually being ready to count.  That might vary for xspress3 v xspress3-mini.   I've tried to track that down a couple of times - it seems to me that is at the driver / xspress3 interface level, but I'm not certain that it couldn't be made faster.  It is also possible that this delay is different for the xspress3 mini.

**Comment by MarkRivers** [comment]
> It looks like it started collecting at
14:27:13.509 and again at 14:27:17.159

No, the first message is “Starting …”, the second message is “Started …”.  In between those 2 asynPrint calls in writeInt32 are only these calls that could take any time:

	    xsp3_status = xsp3->histogram_stop(xsp3_handle_, -1);
	    xsp3_status = xsp3->histogram_clear(xsp3_handle_, 0, xsp3_num_channels, 0, xsp3_time_frames);
            setupITFG();
	    xsp3_status = xsp3->histogram_start(xsp3_handle_, -1 );

Those calls are taking 3.6 seconds. Oksana needs to add asynPrint calls between each on to figure out where the time is being spent.

**Comment by newville** [comment]
@MarkRivers @oksanagit  Right -- that should be looked at.  Having that "stop and clear" goes back pretty early in the AD 1.9 to AD 2 transition, and I think the main motivation was to clear both the "current frame" and "accumulated frame" (now from a PROC record).  

I may have some time this afternoon or early next week to look at this too.

**Comment by oksanagit** [comment]
Thank you @newville  and @MarkRivers . I put the debugging statements as Mark suggested
```            asynPrint(this->pasynUserSelf, ASYN_TRACE_FLOW, "%s Starting Data Collection.\n", functionName);
            //MNewville:  explicitly stop and clear histogram before starting.
            getIntegerParam(xsp3NumFramesDriverParam, &xsp3_time_frames);
            getIntegerParam(xsp3NumChannelsParam, &xsp3_num_channels);
// OI debugging delay acquision start
            asynPrint(this->pasynUserSelf, ASYN_TRACE_FLOW, "%s histogram_stop.\n", functionName);
            xsp3_status = xsp3->histogram_stop(xsp3_handle_, -1);
// OI debugging delay acquision start
            asynPrint(this->pasynUserSelf, ASYN_TRACE_FLOW, "%s histogram_clear.\n", functionName);
            xsp3_status = xsp3->histogram_clear(xsp3_handle_, 0, xsp3_num_channels, 0, xsp3_time_frames);
// OI debugging delay acquision start
            asynPrint(this->pasynUserSelf, ASYN_TRACE_FLOW, "%s setupITFG().\n", functionName);
            setupITFG();
// OI debugging delay acquision start
            asynPrint(this->pasynUserSelf, ASYN_TRACE_FLOW, "%s histogram_start.\n", functionName);
            xsp3_status = xsp3->histogram_start(xsp3_handle_, -1 );
            if (xsp3_status != XSP3_OK) {
                checkStatus(xsp3_status, "xsp3_histogram_start", functionName);
                status = asynError;
            }
            if (status == asynSuccess) {
              epicsEventSignal(this->startEvent_);
              asynPrint(this->pasynUserSelf, ASYN_TRACE_FLOW, "%s Started Data Collection.\n", functionName);
            }
        }
      }
```
Which indicates that the time is taken by histogram_clear
```
2021/06/24 10:03:09.991 Xspress3::writeInt32 asynUser->reason: 8, value: 1, addr: 0
2021/06/24 10:03:09.991 Xspress3::checkConnected Checking connected status.
2021/06/24 10:03:09.991 Xspress3::writeInt32 Starting Data Collection.
2021/06/24 10:03:09.991 Xspress3::writeInt32 histogram_stop.
2021/06/24 10:03:09.992 Xspress3::writeInt32 histogram_clear.
2021/06/24 10:03:10.015 XSP3 addr 0 queueRequest priority 0 not lockHolder
2021/06/24 10:03:10.015 XSP3 addr 0 queueRequest priority 0 not lockHolder
2021/06/24 10:03:13.751 Xspress3::writeInt32 setupITFG().
2021/06/24 10:03:13.751 Xspress3::writeInt32 histogram_start.
xsp4_system_start_count_enb: Xsp3Sys[path].run_flags=0xC
2021/06/24 10:03:13.760 Xspress3::writeInt32 Started Data Collection.
2021/06/24 10:03:13.760 Got start event.
2021/06/24 10:03:13.760 asynManager::portThread port=XSP3 callback
2021/06/24 10:03:13.760 Collect 1 frames
2021/06/24 10:03:13.760 asynManager::portThread port=XSP3 callback
```
What "XSP3 addr 0 queueRequest priority 0 not lockHolder" could mean?

**Comment by newville** [comment]
@oksanagit   What happens to the dataframe if you don't do that clear()?    That is, I'm not certain that is needed for every acquire.

**Comment by mdmoo1978** [comment]
As the one who transition the code from 1.9 to 2.0, I can say that clear is related to something that Quantum Detectors had told me was required. That being said, it could be done in advance of starting to acquire again.

**Comment by MarkRivers** [comment]
> What "XSP3 addr 0 queueRequest priority 0 not lockHolder" could mean?

Those are normal messages printed by asynManager when device support calls pasynManager->queueRequest to queue a request to call the driver.  If you look at your original IOC output you will see a series of 4 messages like this that repeat every 0.1 second:
```
2021/06/23 14:27:13.449 XSP3 addr 0 queueRequest priority 0 not lockHolder
2021/06/23 14:27:13.449 XSP3 addr 0 queueRequest priority 0 not lockHolder
2021/06/23 14:27:13.449 asynManager::portThread port=XSP3 callback
2021/06/23 14:27:13.449 asynManager::portThread port=XSP3 callback
```
I think that probably means there are 2 records that are periodically processing at 10Hz and calling the driver.  They queue the request, and then almost instantly the queue request completes and the "XPS3 callback" message is printed by the callback function. The exception to that timing is when the driver is busy for 3.6 seconds.  During that time it has the lock, so the queue requests happen at 13.549, but the callbacks do not happen until the lock is freed at 17.159.

**Comment by oksanagit** [comment]
@newville I 'm not sure what "in advance" could mean for the step scan, where user moves monochromator, and acquires one spectra. This delay will be there in any case. I am trying to test if removing clear will affect anything as much as I can judge.... Our user says that 1.9 version does not have this delay. Since both drivers run with the same hardware, the Quantum API requirements should not be different, I think

**Comment by oksanagit** [comment]
1. I have commented out the culprit system call histogram_clear() as Matt suggested and was able to test with the user and the beam. We have collected a few single spectra by manually pressing Acquire. We observed no delays, the spectra looked right, and the user was very happy.  More tests are planned for Monday.
2. I was also able to get a hold of another system with 1.9 deployment (?, this is legacy system with not much history details), and ran same test collecting one frame with available tracing.  It looks like the delay is present there as well.

``` 
epics> 2021/06/24 18:45:34.335 XSP3 addr 0 queueRequest priority 0 not lockHolder
2021/06/24 18:45:34.336 asynManager::portThread port=XSP3 callback
2021/06/24 18:45:34.336 Xspress3::writeInt32 Calling writeInt32.
2021/06/24 18:45:34.336 Xspress3::writeInt32 asynUser->reason: 63, value: 1, addr: 0
2021/06/24 18:45:34.336 Xspress3::checkConnected Checking connected status.
2021/06/24 18:45:34.336 Xspress3::writeInt32 Starting Data Collection.
2021/06/24 18:45:34.393 Xspress3::writeInt32 Started Data Collection.
2021/06/24 18:45:34.394 Xspress3::dataTask Got Start Event.
2021/06/24 18:45:38.625 Xspress3::dataTask frame_count: 1.
2021/06/24 18:45:38.628 Xspress3::dataTask frame_count: 1.
2021/06/24 18:45:38.628 Xspress3::dataTask framesToReadOut: 1.
2021/06/24 18:45:38.628 Xspress3::dataTask frameCounter: 1.
```
I will have an opportunity to test the original system with 1.9 driver to confirm that the delay is present there or Not.    

It would be nice to understand what histogram_clear() does .... so that the collected data remain valid
Thank you

**Comment by mdmoo1978** [comment]
If my memory serves me, if that clear isn’t ever called between acquires, the spectra sum.

**Comment by MarkRivers** [comment]
It seems like NSLS-II is seeing longer delays in the call to histogram_clear than Matt is at APS.  We need to figure out if this is due to different hardware, different versions of Quantum software, or something else.  It should probably be reported to Quantum, since it may be something they have seen before.

**Comment by newville** [comment]
@oksanagit yes, I am looking at this right now with our system (7-channel Xspress3 original, not mini).

Commenting out the "clear()" in the driver means that I must do a caput to the ERASE field prior to starting an acquisition or else the spectra acquired are summed with the previous spectra.  

It's OK with me to leave the driver like this, but then really, really have to put an ERASE in the "arm" phase.  I checked this for mapping mode (fly-scan with 1 "start" and triggers saving full spectra to HDF5), XAFS ROI mode (fly-scan with 1 "start", and saving ROIStats data), and simple step scan mode.   

For step scan mode, an ERASE absolutely needs to be done for each point in the scan.    Otherwise, you are accumulating data.    It might be that the BNL scanning code based on AD19 was doing that, and so when using the latest version was effectively ERASEing twice.

For my system, doing 

     prefix = '13QX7'
     caput(f'{prefix}:det1:ERASE', 1, wait=True)

takes between 0.2 to 0.25 seconds.

Again, I would be OK with leaving that ERASE commented out -- it just means that all of the downstream applications have to change to do an ERASE in the "arming" process, and not rely on it happening after Start.    An alternative might be to add an EraseStart field that does both.

Having separate Start, Erase, and EraseStart might make the most sense.   Opinions?

**Comment by oksanagit** [comment]
I have ran a few tests today on 8 channel xspress3. 

Commenting out the[ xsp3->histogram_clear()](https://github.com/epics-modules/xspress3/blob/cc511b1ea2c5c559dcdb22001784860572514150/xspress3App/src/xspress3Epics.cpp#L1170 ) did not change the functionality for me with this line preset or not,  except the delay at the beginning of the the spectra collection, when the line is present. Which is different from what Matt reported, if we are talking about the same line.  In both cases  in order to erase the spectra one needs to write 1 to $P$R:det1:ERASE. First write erases MSC1:ArraytData, second write erases MCASUM1:ArrayData.  However, there is no need to do this. New MCA1:ArrayData shows the correct spectra in the step scan. We do not care about the sum anyways, but if one does erase could be done via a PV as needed.  

Also, we have tried to see if the delay is present with Quantum distributed IOC and collect some logs.
Delay is not there, just as the user reported. It could be that Quantum figured out it a while ago and removed this line... (?) I wonder if there is a code we could confirm this with. And I wasn’t successful enabling logs for this IOC to see the insights.

**Comment by newville** [comment]
@oksanagit I'm pretty sure that when that `xsp3->histogram_clear()` is commented out of the Start method, that the current frame is not erased.  In some cases, that is a desirable feature, but for sure, not doing that erase will change the behavior.   

I think it is fine to change to have a Start that does not first Erase, but doing an Erase will definitely, definitely be needed. 

It is likely that any application using the 1.9 driver *was* doing an ERASE before starting a collection, as that was necessary unless you wanted frames to accumulate.   So, if you're reporting what the downstream data collection was working and is now still working, I suspect that it was doing an Erase before each Start -- it probably had too, and now definitely has to.  Please confirm that you can do a 10-second acquisition, change the dwell time to 0.01 second, hit Start without Erase, and verify that the counts go way down.

It's possible that doing two erases in quick succession could be a part of the problem.  In fact, I see this:

```
>>> from epics import get_pv
>>> from time import time
>>> erase_pv = epics.get_pv('13QX7:det1:ERASE')
>>> erase_pv.connect()
>>> t0  = time(); erase_pv.put(1, wait=False) ; print(time()-t0)
1
0.00020503997802734375
>>> t0  = time(); erase_pv.put(1, wait=True) ; print(time()-t0)
1
0.2312467098236084
>>> t0  = time(); erase_pv.put(1, wait=False) ; erase_pv.put(1, wait=True) ; print(time()-t0)
1
1
0.43349695205688477

```

which is to say:  hitting Erase twice in a row is 2x slower than hitting it once.  It's still not 3 seconds for me and I don't understand why it is for you.  But, for sure, if we keep that Erase out Start (and I lean to yes -- we've been running like this since Friday), then one absolutely has to make sure that Erase is hit once, and apparently "only once".    I did not have that Erase in my Xspress3 code before, and I definitely needed to add this to the "Arm detector" function that gets run once before each fly scan or for each point in a step scan.

**Comment by oksanagit** [comment]
Hi @newville , Sorry for delay. We have run the test as you described and MCA[N]:ArrayData behaved correctly:  10 second exposure: ~900 kcounts/channel.  0.1 second exposure ~9 kcounts/channel.  I will created a PR rather to be very explicit  what line has been commented out.  I wonder how this change behaves for you

**Comment by newville** [comment]
@oksanagit do you mean you see that without doing an explicit ERASE, but only with Acquire?  I definitely do not see that.   I see that if I Acquire without doing an ERASE, the frames accumulate.  And that matches my expectation: Acquire will continue counting into the current frame.  

With the ERASE commented out of the driver code as you have it, running this code: 

```python
import time
from epics import get_pv

prefix = '13QX7'
acquire    = get_pv(f'{prefix}:det1:Acquire')
erase      = get_pv(f'{prefix}:det1:ERASE')
dwelltime  = get_pv(f'{prefix}:det1:AcquireTime')
numimages  = get_pv(f'{prefix}:det1:NumImages')
mca1data   = get_pv(f'{prefix}:MCA1:ArrayData')
clockticks = get_pv(f'{prefix}:C1SCA:0:Value_RBV')

# 1: fresh 5 second exposure, after erase
numimages.put(1)
dwelltime.put(5)
erase.put(1, wait=True)
time.sleep(0.1)
acquire.put(1, wait=True)
time.sleep(0.1)
print(f'erase then 5.0 sec exposure: {mca1data.get().sum():13.0f} counts {clockticks.get():13.0f} ticks')

# 2: 1 second exposue, no erase
dwelltime.put(1)
time.sleep(0.1)
acquire.put(1, wait=True)
time.sleep(0.1)
print(f'no erase,  0.5 sec exposure: {mca1data.get().sum():13.0f} counts {clockticks.get():13.0f} ticks')

# 3: erase, and then 0.1 second exposue
dwelltime.put(1)
erase.put(1, wait=True)
time.sleep(0.1)
acquire.put(1, wait=True)
time.sleep(0.1)
print(f'erase then 0.5 sec exposure: {mca1data.get().sum():13.0f} counts {clockticks.get():13.0f} ticks')
```

gives (with no X-rays hitting the detector but a bit of noise)

```bash
erase then 5.0 sec exposure:           112 counts     400000000 ticks
no erase,  0.5 sec exposure:           139 counts     480000000 ticks
erase then 0.5 sec exposure:            16 counts      80000000 ticks
```

That is, even without beam you should be able to tell that 2 Acquires in a row without an ERASE in between will be accumulating data into the spectrum.

This is what we at the APS saw when we first got the Xspress3, and why we changed the code.  The data collection systems at the time (still used at many APS beamlines), rely on the Epics SSCAN record, which does not have an "arm" concept, and more or less require that there be 1 PV that you send a 1 to with a "wait callback" that only returns when the detector is done counting -- a "busy" record.     We opted to just make Acquire be that busy record: it is rare to need to add more data into an already accumulated spectrum, and data collection tools could just acquire multiple spectra and add them downstream.

If you all at NSLS-II were relying on the QD 1.9 driver, it probably did not have this fix and your data collection scripts probably have an ERASE before each Acquire. If you were collecting XAFS data in step scan mode, then that "ERASE" has to be somewhere -- either in your scrips or in the driver, the data would have been accumulating at each step.

I am pretty sure that the Epics interface will need to have a busy record that is an "Erase and Start" method so that the SSCAN record can work to collect data with the Xspress3.   It is OK with me to have a separate "Start" and "EraseStart" method but I think that EraseStart is actually necessary to match the behavior of essentially all other Area, Counting, and Spectroscopy detectors.

Another option would be to restore that "ERASE" to the Xspress3 driver and not have explicit ERASE in your data collection code.    I sort of think that having both "Start" and "EraseStart" is probably better, as it would match most other XRF detectors, though (I think) not very many areaDetectors.

**Comment by oksanagit** [comment]
> @oksanagit do you mean you see that without doing an explicit ERASE, but only with Acquire? 

Yes, I do, and I see this using CSS interface, not with data collection code. Our version uses areaDetector 3.8. Which version are you using? 
It is very difficult to believe that the same code produces different outcomes. And assuming that xspress3 API is the same for both of us, I agree that erase() should be called at some point. There are only a few places in the code to trace. I will try to figure this out at my next opportunity with the system. 
I think it is important to understand why the driver behaves differently for APS and NSLS-II.

**Comment by newville** [comment]
@oksanagit The behavior is not dependent on the version of areadetector (well 3.5 or higher, that is).  FWIW, I'm using ADCore 3.10.0. 

What are the results when you run the script I included above?   I do not understand how the clock ticks can be reset to 0 unless you do an ERASE.  With that ERASE removed from the "ADAcquire" code, the behavior I see seems completely sensible to me.    

That is also easy to see from any of the display screens.   Set Numframes=1, Dwell Time=1, hit the "Erase" button.  The clock ticks will read 0.  Hit the "Start" button and after a second, clock ticks will read 80,000,000.  Hit "Start" again, and clock ticks will read 160,000,000, not 80,000,000  Again, that all makes perfect sense to me, and it is all working correctly.    "Start" is not Erasing, just as we told it to no longer do.

Just to be clear, I pushed this change to `Xspress3Epics.cpp` to the `no_erase` branch.

**Comment by oksanagit** [comment]
> What are the results when you run the script I included above?

```
erase then 5.0 sec exposure:             0 counts     400000000 ticks
no erase,  0.5 sec exposure:             0 counts      80000000 ticks
erase then 0.5 sec exposure:             0 counts      80000000 ticks
```
Shall we check the API library version? I am not sure how.  As of now I have just one detector to test this code. It is 8 channel one, recently acquired.

**Comment by MarkRivers** [comment]
@oksanagit what branch of Xspress3 are you using?

**Comment by oksanagit** [comment]
```
[xspress3@xspress3 xspress3]$ git branch 
* 8ChannelsIOC
  master
[xspress3@xspress3 xspress3]$ 
```

From the times I created a PR for 8 channel IOC.  I can't pull and merge now, or I don't know how. This server got cut out from the outside world.

**Comment by newville** [comment]
@oksanagit  I don't see a branch name "8ChannelsIOC" here.   That makes it hard to know we're running the same code.  Are you sure that this has that ERASE removed?    Maybe try the `no_erase` branch here?

I am pretty sure that if you're seeing the clock ticks be reset, that something must be calling that 'xsp3_histogram_clear()'.  You might try separately monitoring the ERASE PV, though that would only capture if something did that from CA, not from within the driver code.   The asyn trace calls might help track those down.    Otherwise, this is all very confusing.

**Comment by oksanagit** [comment]
"8ChannelsIOC" was a PR #20,  you merged it on Mar 17, 2021. I see you updated libraries from quantum on master after this. Are you using them now? I do not. 

I put printf in xsp3Api.cpp: int xsp3Api::histogram_clear() before [this line](https://github.com/epics-modules/xspress3/blob/cc511b1ea2c5c559dcdb22001784860572514150/xspress3App/src/xsp3Api.cpp#L148):  https://github.com/epics-modules/xspress3/blob/cc511b1ea2c5c559dcdb22001784860572514150/xspress3App/src/xsp3Api.cpp#L148  
This is not being called by # 2 and is called by # 1 and # 3 of your python script.

My code is not calling histogram_clear() when asked to acquire, I created a PR #24 to share the changes. I did comment out this line: 
https://github.com/epics-modules/xspress3/blob/cc511b1ea2c5c559dcdb22001784860572514150/xspress3App/src/xspress3Epics.cpp#L1170


This is very confusing, agree.  The system I have is actively used, and not connected to internet anymore. I will try to get in last two commits to master in some graceful way if you are using them too.

**Comment by newville** [comment]
@oksanagit Sorry,  I really do not understand your report at all.  

> I see you updated libraries from quantum on master after this. Are you using them now? I do not.

I am running with the code in the `no_erase` branch.  I get the expected behavior for ERASE and Acquire.

> I put printf in xsp3Api.cpp: int xsp3Api::histogram_clear() before this line:
> 
> xspress3/xspress3App/src/xsp3Api.cpp
>
>Line 148 in cc511b1
>
> status = xsp3Api_histogram_clear( path, first_chan, num_chan, first_frame, num_frames); 
>
> This is not being called by # 2 and is called by # 1 and # 3 of your python script.

Yes, of course.  When you put a 1 to the ERASE PV, this code is supposed to get called.    And when I send a 1 to ERASE this code does get called, when I send a 1 to Acquire, it does not.  

> My code is not calling histogram_clear() when asked to acquire, I created a PR #24 to share the changes. 

Yes, that is essentially the same as the "no_erase" branch. Are you not running that branch but older code in the 8ChannelIOC branch, before this change was made?   That would explain the difference -- the behavior you see is consistent with calling histogram_clear() on Acquire.  I thought you did not want that.   

I don't really know what to tell you.   As far as I can tell, everything is working correctly on the `no_erase` branch.  Well, expect that we have not added an EraseStart.

**Comment by newville** [comment]
@oksanagit So, I've been thinking about this issue, and I have come to believe that while need both an "EraseStart" and separate "Erase" and "Start", that we should back up a bit:

That is, I think we should preserve `det1:Acquire` to be "Erase Start".   As far as I can tell `det1:Acquire` is "acquire into a new frame" for all other area detectors.   Changing that here now to be only "Start" would break all the existing uses of this module, including anyone using the Epics SSCAN record or Spec - so probably most APS users.

But, we should add a "Start", as `det1:Start` that begins acquisition without an ERASE.  Just to be clear, I'm going to use that too -- ERASE is slow enough that doing that "ERASE" in an "arm detector" sequence is definitely more efficient (that is, can be done in parallel with other arming tasks, including setting FileSaver data and moving positioners to their starting positions).

Does that make sense and seem reasonable to you?

I'll try to do that tomorrow, working in the `no_erase` branch, but I'm not sure I will get that done. And, as the end of the APS run approaches and Virtual Summer Schools loom, it may not happen until later in August.

**Comment by oksanagit** [comment]
@newville , I still did not have an opportunity to test the no_erase branch, to make sure we run the same code. It seems impossible for us to have different outcome with the same code. I would like to understand this behavior. I will report here as soon as I get an opportunity with the system.

Adding new records will not really benefit us, because our data acquisition framework is using standard areaDetector support, same as for you, I understand.  But it is totally OK for now to keep things as is, and for us to work from another brunch until we figure out something perfect. I am sure the right solution will reveal itself at some point.
Please keep no_erase branch as is for now.

**Comment by newville** [comment]
@oksanagit Well, I think that the main branch does follow the AD conventions:  `det1:Acquire` should acquire a new image frame, not adding to the existing image.   The AD19 Xspress3 support did not do this, so you needed to add an explicit ERASE before each Acquire in your client code.  

If you were using the main branch, one option would be to take that explicit ERASE out of the client code: it is unnecessary and slows you down.  What I'm proposing is to leave that "normal AD behavior" (and also the existing behavior that many of us have been using for several years) be the default.

But also, because ERASE is noticeably slow (I am sure it should not be 3 seconds, but it might be 0.5 seconds -- I se around 0.25 seconds), it would be helpful for those of who collect data with separate "Arm detector" and "Start Detector" processes.  I *think* that includes the NSLS-II data collection, and I know it included my system.  So, I would like to add a separate "Start without ERASE"  PV, so that we can ERASE while also arming other detectors and moving positioners to the starting (or next) position.  I think that would be better for all of us who could use that approach as the actual collection time of the various detectors will better align in time.  

I hope that makes sense!

**Comment by newville** [comment]
@oksanagit The latest release (3.2.7) should have dramatically faster time for ERASE.  It no longer erases all available (12000+) frames, just the most recently used frames.  For cases where that number of most recent frames is 1 or 10, or even 500, that time is actually significantly faster, more like a couple milliseconds rather than 300+ milliseconds.
